image:
  repository: ghcr.io/xiaxing12/myapp        # 改这里
  tag: "latest"                              # 改这里
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80                             # 改这里